services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # Don't mount node_modules from host
    environment:
      - NODE_ENV=development
